// "New pitches": questions in the same skill FAMILY as Levi's misses, but on a
// different rule than the one he missed. Each is tagged with the ACT College &
// Career Readiness Standard it tests (ACT's own skill codes, from
// act.org/content/dam/act/unsecured/documents/CCRS-EnglishStandards.pdf).
// Same fields as questions.js, with kind: "cousin". Choice order after
// "No Change" is shuffled at play time, so write them in any order.

QUESTIONS.push(
  // ---------- Subject-verb agreement family ----------
  {
    id: "c-sva1", kind: "cousin", code: "USG 601", skill: "inverted order: verb before subject",
    rule: "Subject-verb agreement", from: "ACT USG 601",
    passage: "Beyond the left-field wall [[sits]] a bullpen, a picnic area, and a small souvenir stand.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "sit", "is sitting", "has sat"],
    answer: 1, trap: 0,
    why: "Flip it around: \"a bullpen, a picnic area, and a souvenir stand sit.\" Three things joined by and make a plural subject.",
    trapWhy: "Sits matches \"wall,\" the only noun before the verb. When the verb comes first, find the subject AFTER it.",
  },
  {
    id: "c-sva2", kind: "cousin", code: "USG 601", skill: "indefinite pronoun: neither",
    rule: "Subject-verb agreement", from: "ACT USG 601",
    passage: "Neither of the team's catchers [[have thrown]] out a base runner this week.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "has thrown", "are throwing", "were throwing"],
    answer: 1, trap: 0,
    why: "Neither means \"not one,\" so it's singular: neither has thrown.",
    trapWhy: "Have agrees with \"catchers.\" Same move as \"one of the notes\": the plural noun is inside an of-phrase.",
  },
  {
    id: "c-sva3", kind: "cousin", code: "USG 601", skill: "either/or: verb matches the closer subject",
    rule: "Subject-verb agreement", from: "ACT USG 601",
    passage: "Either the manager or his pitching coaches [[decides]] when a tired starter leaves the game.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "decide", "has decided", "is deciding"],
    answer: 1, trap: 0,
    why: "With either/or, the verb matches the subject closest to it. That's coaches, which is plural, so decide.",
    trapWhy: "Decides matches \"manager,\" but with or/nor the nearer subject wins.",
  },
  {
    id: "c-sva4", kind: "cousin", code: "USG 701", skill: "\"along with\" doesn't make a plural",
    rule: "Subject-verb agreement", from: "ACT USG 701",
    passage: "The shortstop, along with two of his teammates, [[visit]] the children's hospital every December.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "visits", "have visited", "are visiting"],
    answer: 1, trap: 0,
    why: "The subject is shortstop. \"Along with two of his teammates\" is an interruption, not part of the subject, so visits.",
    trapWhy: "Visit treats it like \"the shortstop and two teammates.\" Only and makes a plural; along with, as well as and together with don't.",
  },
  {
    id: "c-sva5", kind: "cousin", code: "USG 601", skill: "\"there is / there are\"",
    rule: "Subject-verb agreement", from: "ACT USG 601",
    passage: "During a regular-season game, there [[is]] four umpires on the field, one at each base and one behind the plate.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "are", "was", "has been"],
    answer: 1, trap: 0,
    why: "\"There\" is never the subject. The subject is four umpires, so are.",
    trapWhy: "\"There is\" sounds natural because people say it all the time, but the real subject comes after the verb and it's plural.",
  },
  {
    id: "c-sva6", kind: "cousin", code: "USG 302", skill: "collective noun: team is singular",
    rule: "Subject-verb agreement", from: "ACT USG 302",
    passage: "After a slow start in April, the team [[has won]] eleven of its last twelve games.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "have won", "are winning", "were winning"],
    answer: 0, trap: 1,
    why: "Team is one group, so it's singular: has won. The sentence's own \"its\" confirms it.",
    trapWhy: "Have won thinks of all the players. On the ACT, a team, a crowd or a band is singular.",
  },

  // ---------- Pronoun family ----------
  {
    id: "c-pr1", kind: "cousin", code: "USG 502", skill: "pronoun refers back across sentences",
    rule: "Pronoun and verb agreement", from: "ACT USG 502",
    passage: "Every rookie received two new gloves at the start of spring training. By opening day, most of the rookies had broken [[it]] in.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "them", "him", "its"],
    answer: 1, trap: 0,
    why: "The pronoun points back to gloves in the sentence before, which is plural, so them.",
    trapWhy: "It would need one glove. Go back to the sentence before and find what the pronoun stands for.",
  },
  {
    id: "c-pr2", kind: "cousin", code: "USG 503", skill: "vague pronoun",
    rule: "Pronoun and verb agreement", from: "ACT USG 503",
    passage: "When the pitcher threw the ball to the catcher, [[he]] dropped it.",
    stem: "Which choice makes the sentence clearest?",
    choices: ["No Change", "the catcher", "they", "him"],
    answer: 1, trap: 0,
    why: "Two people could be \"he.\" Naming the catcher removes the confusion.",
    trapWhy: "He could mean the pitcher or the catcher. On the ACT, a pronoun that could point to two people is wrong even if you can guess.",
  },
  {
    id: "c-pr3", kind: "cousin", code: "USG 602", skill: "who vs. whom",
    rule: "Pronoun and verb agreement", from: "ACT USG 602",
    passage: "The scout, [[who]] the team had hired only a month earlier, discovered the young pitcher in a summer league.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "whom", "which", "whose"],
    answer: 1, trap: 0,
    why: "Rearrange it: \"the team had hired him.\" Him means whom.",
    trapWhy: "Who is for he/she (doing the action). Here the scout is the one being hired, so the him-form, whom.",
  },
  {
    id: "c-pr4", kind: "cousin", code: "USG 602", skill: "its vs. it's",
    rule: "Pronoun and verb agreement", from: "ACT USG 602",
    passage: "[[Its]] never easy to hit a curveball that breaks late and low.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "It's", "Its'", "They're"],
    answer: 1, trap: 0,
    why: "The sentence means \"It is never easy,\" and it is = it's.",
    trapWhy: "Its (no apostrophe) means \"belonging to it.\" Say it out loud as \"it is\"; if that works, you need the apostrophe.",
  },
  {
    id: "c-pr5", kind: "cousin", code: "SST 502", skill: "pronoun person shift",
    rule: "Pronoun and verb agreement", from: "ACT SST 502",
    passage: "When fans catch a foul ball, [[you]] usually hold it up for the television cameras.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "they", "we", "one"],
    answer: 1, trap: 0,
    why: "The sentence is about fans, so the pronoun stays in third person plural: they.",
    trapWhy: "You switches from talking about fans to talking to the reader. Keep the pronoun in the same person as its noun.",
  },
  {
    id: "c-pr6", kind: "cousin", code: "USG 602", skill: "reflexive pronoun misuse",
    rule: "Pronoun and verb agreement", from: "ACT USG 602",
    passage: "Before the game, the equipment manager asked Marcus and [[myself]] to carry the bat bags to the dugout.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "me", "I", "ourselves"],
    answer: 1, trap: 0,
    why: "Drop \"Marcus and\": \"asked me to carry.\" So me.",
    trapWhy: "Myself only works when \"I\" already appears in the sentence (\"I carried it myself\"). It sounds formal, but it's wrong here.",
  },

  // ---------- Tone and word choice family ----------
  {
    id: "c-t1", kind: "cousin", code: "KLA 401", skill: "redundancy in one phrase",
    rule: "Tone and register", from: "ACT KLA 401",
    passage: "The crowd rose to its feet [[and stood up]] as the ball cleared the wall.",
    stem: "Which choice is most effective?",
    choices: ["No Change", ", standing up,", "and got up", "Delete the underlined portion."],
    answer: 3, trap: 1,
    why: "\"Rose to its feet\" already means stood up. Delete it.",
    trapWhy: "Rewording the repetition doesn't fix it. When a choice says the same thing twice, look for DELETE.",
  },
  {
    id: "c-t2", kind: "cousin", code: "KLA 502", skill: "wordiness",
    rule: "Tone and register", from: "ACT KLA 502",
    passage: "The umpires stopped the game in the sixth inning [[due to the fact that]] lightning had been spotted nearby.",
    stem: "Which choice is most effective?",
    choices: ["No Change", "because", "on account of the fact that", "owing to the reason that"],
    answer: 1, trap: 0,
    why: "Because says the same thing in one word. The ACT rewards the shortest version that keeps the meaning.",
    trapWhy: "\"Due to the fact that\" sounds official, but it's five words doing one word's job.",
  },
  {
    id: "c-t3", kind: "cousin", code: "USG 603", skill: "confused words: allude/elude",
    rule: "Tone and register", from: "ACT USG 603",
    passage: "The runner [[alluded]] the tag by sliding around the catcher and slapping the plate with his hand.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "eluded", "illuded", "deluded"],
    answer: 1, trap: 0,
    why: "Elude means to escape or dodge, which is what the runner did.",
    trapWhy: "Allude means to hint at something. The two sound almost the same, which is exactly why the ACT pairs them.",
  },
  {
    id: "c-t4", kind: "cousin", code: "KLA 503", skill: "tone: slang in a formal essay",
    rule: "Tone and register", from: "ACT KLA 503",
    passage: "The architects who designed the new ballpark studied dozens of older stadiums. They [[were pumped that they]] could keep the famous frieze that lines the roof.",
    stem: "Which choice most effectively maintains the essay's tone?",
    choices: ["No Change", "were pleased that they", "went totally nuts that they", "rejoiced with boundless, unrestrained ecstasy that they"],
    answer: 1, trap: 0,
    why: "\"Were pleased\" is formal and neutral, like the rest of the passage.",
    trapWhy: "\"Pumped\" is how you'd text it, not how you'd write an informative essay. The over-the-top option fails the other way.",
  },
  {
    id: "c-t5", kind: "cousin", code: "KLA 602", skill: "redundancy that sounds fine in conversation",
    rule: "Tone and register", from: "ACT KLA 602",
    passage: "Babe Ruth hit 60 home runs in 1927, a single-season record [[that stood unbroken and unmatched]] for thirty-four years.",
    stem: "Which choice is most effective?",
    choices: ["No Change", "that stood", "that remained standing and unbroken", "which lasted and endured"],
    answer: 1, trap: 2,
    why: "A record that \"stood\" was already unbroken. The shorter version keeps the whole meaning.",
    trapWhy: "Every long choice repeats itself. If the shortest answer is grammatical and keeps the meaning, it's usually right.",
  },
  {
    id: "c-t6", kind: "cousin", code: "KLA 401", skill: "redundancy in one phrase",
    rule: "Tone and register", from: "ACT KLA 401",
    passage: "[[In my personal opinion, I think]] the seventh-inning stretch is the best tradition in baseball.",
    stem: "Which choice is most effective?",
    choices: ["No Change", "I think", "In my opinion, I personally think", "Personally, in my own view, I think"],
    answer: 1, trap: 0,
    why: "\"I think\" already means it's your opinion. Say it once.",
    trapWhy: "\"In my personal opinion, I think\" says \"my opinion\" three ways.",
  },

  // ---------- Transitions and connecting words family ----------
  {
    id: "c-tr1", kind: "cousin", code: "KLA 504", skill: "conjunction between clauses: although",
    rule: "Transitions", from: "ACT KLA 504",
    passage: "[[Although]] the rookie had struck out in his first three at-bats, he lined the game-winning single in the ninth.",
    stem: "Which choice is most logical in context?",
    choices: ["No Change", "Because", "Since", "So that"],
    answer: 0, trap: 1,
    why: "Striking out three times and then winning the game is a contrast, and although sets one up.",
    trapWhy: "Because would mean the strikeouts caused the hit. Check whether the two halves agree or clash.",
  },
  {
    id: "c-tr2", kind: "cousin", code: "ORG 501", skill: "cause and effect",
    rule: "Transitions", from: "ACT ORG 501",
    passage: "Half of the stadium's light towers went dark in the fifth inning. [[However,]] the umpires suspended the game until the next afternoon.",
    stem: "Which transition word is most logical in context?",
    choices: ["No Change", "Consequently,", "For example,", "Similarly,"],
    answer: 1, trap: 0,
    why: "The lights failing caused the suspension. That's cause and effect.",
    trapWhy: "However signals a contrast, but nothing here is surprising. The second sentence is the result of the first.",
  },
  {
    id: "c-tr3", kind: "cousin", code: "ORG 401", skill: "time order",
    rule: "Transitions", from: "ACT ORG 401",
    passage: "The groundskeepers arrive at dawn to water the infield. [[In contrast,]] they drag the dirt smooth and paint the foul lines.",
    stem: "Which transition word is most logical in context?",
    choices: ["No Change", "Afterward,", "Nevertheless,", "For instance,"],
    answer: 1, trap: 0,
    why: "These are the next steps in the same routine, so a time word fits.",
    trapWhy: "In contrast needs an opposite. Watering and painting aren't opposites — they're steps in order.",
  },
  {
    id: "c-tr4", kind: "cousin", code: "KLA 603", skill: "conjunction inside a sentence: but vs. so",
    rule: "Transitions", from: "ACT KLA 603",
    passage: "The fly ball looked certain to land foul, [[so]] it curved back at the last second and struck the foul pole for a home run.",
    stem: "Which choice is most logical in context?",
    choices: ["No Change", "but", "because", "and so"],
    answer: 1, trap: 0,
    why: "It looked foul, but it turned out fair. That's a surprise, so but.",
    trapWhy: "So means the second part follows from the first. Looking foul didn't cause the ball to curve fair.",
  },
  {
    id: "c-tr5", kind: "cousin", code: "ORG 501", skill: "similarity",
    rule: "Transitions", from: "ACT ORG 501",
    passage: "Pitchers study video of opposing hitters before every series. [[Instead,]] hitters review footage of the pitchers they are likely to face.",
    stem: "Which transition word is most logical in context?",
    choices: ["No Change", "Similarly,", "Consequently,", "In contrast,"],
    answer: 1, trap: 3,
    why: "Both sides do the same kind of homework, so the relationship is similarity.",
    trapWhy: "In contrast looks tempting because pitchers and hitters are opposites, but the sentences describe the same action. Judge the ideas, not the people.",
  },
  {
    id: "c-tr6", kind: "cousin", code: "ORG 601", skill: "concession then surprise: nevertheless",
    rule: "Transitions", from: "ACT ORG 601",
    passage: "The forecast called for heavy rain all evening. [[Therefore,]] more than forty thousand fans showed up for the game.",
    stem: "Which transition word is most logical in context?",
    choices: ["No Change", "Nevertheless,", "For example,", "Likewise,"],
    answer: 1, trap: 0,
    why: "You'd expect rain to keep fans away, and they came anyway. Nevertheless means \"in spite of that.\"",
    trapWhy: "Therefore says the rain CAUSED the crowd. It's the opposite: the fans came despite the forecast.",
  },

  // ---------- Relative clauses family ----------
  {
    id: "c-r1", kind: "cousin", code: "PUN 602", skill: "comma + which (not that)",
    rule: "Relative pronouns", from: "ACT PUN 602",
    passage: "The current Yankee Stadium[[, that]] cost more than two billion dollars to build, opened in 2009.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", ", which", "which", ", who"],
    answer: 1, trap: 0,
    why: "An extra-information clause set off by commas starts with which, never that.",
    trapWhy: "That never follows a comma. Comma → which; no comma → that.",
  },
  {
    id: "c-r2", kind: "cousin", code: "PUN 701", skill: "no commas around an essential clause",
    rule: "Relative pronouns", from: "ACT PUN 701",
    passage: "Every player[[, who]] takes the field on Jackie Robinson Day wears the number 42.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "who", ", which", "whom"],
    answer: 1, trap: 0,
    why: "\"Who takes the field on Jackie Robinson Day\" tells you WHICH players, so it's essential and takes no commas.",
    trapWhy: "Test it: remove the clause. \"Every player wears the number 42\" changes the meaning, so the clause can't be set off.",
  },
  {
    id: "c-r3", kind: "cousin", code: "USG 602", skill: "whose vs. who's",
    rule: "Relative pronouns", from: "ACT USG 602",
    passage: "The reliever [[who's]] fastball reached 101 miles per hour struck out the side in the eighth.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "whose", "who", "that's"],
    answer: 1, trap: 0,
    why: "The fastball belongs to the reliever, and the possessive is whose.",
    trapWhy: "Who's means \"who is.\" \"The reliever who is fastball\" makes no sense.",
  },
  {
    id: "c-r4", kind: "cousin", code: "SST 301", skill: "relative clause cut off into a fragment",
    rule: "Relative pronouns", from: "ACT SST 301",
    passage: "The ballpark's old scoreboard, which showed only the line score and the [[count. Was]] replaced during a renovation.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "count, was", "count; was", "count, it was"],
    answer: 1, trap: 3,
    why: "The which-clause needs a closing comma, and then the sentence continues to its verb, was.",
    trapWhy: "Adding \"it\" repeats the subject; the scoreboard already is the subject. Close the interruption and keep going.",
  },
  {
    id: "c-r5", kind: "cousin", code: "SST 401", skill: "\"where\" for something that isn't a place",
    rule: "Relative pronouns", from: "ACT SST 401",
    passage: "1996 was the season [[where]] the Yankees won their first championship in eighteen years.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "in which", "which", "that it"],
    answer: 1, trap: 0,
    why: "A season is a time, not a place. \"In which\" works.",
    trapWhy: "Where is only for physical places. It's the same rule you saw with \"where it\" on 25MC1 #31.",
  },
  {
    id: "c-r6", kind: "cousin", code: "SST 401", skill: "which vs. who for people",
    rule: "Relative pronouns", from: "ACT SST 401",
    passage: "The ushers [[which]] work the upper deck know most of the season-ticket holders by name.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "who", "whom", "where"],
    answer: 1, trap: 2,
    why: "Ushers are people and they're doing the working, so who.",
    trapWhy: "Whom is for people receiving the action. Here the ushers are the ones working.",
  },

  // ---------- Punctuation and clause boundaries family ----------
  {
    id: "c-p1", kind: "cousin", code: "PUN 701", skill: "no commas around an essential name",
    rule: "Paired dashes around an interruption", from: "ACT PUN 701",
    passage: "Hall of Fame pitcher[[, Whitey Ford,]] won more games than any other pitcher in franchise history.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "Whitey Ford", ", Whitey Ford", "Whitey Ford,"],
    answer: 1, trap: 0,
    why: "The name is essential: without it you don't know which pitcher. Essential info gets no commas.",
    trapWhy: "The commas are a matched pair, so it looks right. But remove the name and the sentence stops making sense, so it isn't an interruption.",
  },
  {
    id: "c-p2", kind: "cousin", code: "PUN 401", skill: "no comma between subject and verb",
    rule: "Paired dashes around an interruption", from: "ACT PUN 401",
    passage: "The fans packed into the upper [[deck, cheered]] every pitch of the ninth inning.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "deck cheered", "deck; cheered", "deck—cheered"],
    answer: 1, trap: 0,
    why: "\"The fans packed into the upper deck\" is the subject and cheered is the verb. Nothing goes between them.",
    trapWhy: "You pause there when you read it aloud, but a pause isn't a reason for a comma. One mark between a subject and its verb is always wrong.",
  },
  {
    id: "c-p3", kind: "cousin", code: "SST 301", skill: "comma splice",
    rule: "Paired dashes around an interruption", from: "ACT SST 301",
    passage: "The game went fourteen [[innings, it]] didn't end until almost one in the morning.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "innings; it", "innings it", "innings, and, it"],
    answer: 1, trap: 0,
    why: "Both halves are complete sentences. A semicolon can join them; a comma alone can't.",
    trapWhy: "That's a comma splice: two full sentences glued with only a comma. It's one of the most-tested errors on the ACT.",
  },
  {
    id: "c-p4", kind: "cousin", code: "PUN 702", skill: "colon to introduce an explanation",
    rule: "Paired dashes around an interruption", from: "ACT PUN 702",
    passage: "The rookie had only one goal for his first [[season; to]] make the All-Star team.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "season: to", "season, and to", "season. To"],
    answer: 1, trap: 0,
    why: "A colon introduces what the goal is. What comes before it is a full sentence, which is what a colon needs.",
    trapWhy: "A semicolon needs a complete sentence on BOTH sides, and \"to make the All-Star team\" isn't one.",
  },
  {
    id: "c-p5", kind: "cousin", code: "PUN 502", skill: "no colon after a verb",
    rule: "Paired dashes around an interruption", from: "ACT PUN 502",
    passage: "The concession stands behind home plate [[sell:]] hot dogs, soft pretzels, and garlic fries.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "sell", "sell;", "sell—"],
    answer: 1, trap: 0,
    why: "The list is the object of sell, and nothing goes between a verb and its object.",
    trapWhy: "Colons introduce lists only after a complete sentence. \"The concession stands sell\" isn't complete.",
  },
  {
    id: "c-p6", kind: "cousin", code: "PUN 501", skill: "no comma in a compound verb",
    rule: "Paired dashes around an interruption", from: "ACT PUN 501",
    passage: "The shortstop fielded the hard ground ball [[cleanly, and]] threw to first base in one smooth motion.",
    stem: "Which choice makes the sentence most grammatically acceptable?",
    choices: ["No Change", "cleanly and", "cleanly; and", "cleanly, and,"],
    answer: 1, trap: 0,
    why: "One subject (the shortstop) doing two things (fielded and threw) takes no comma before and.",
    trapWhy: "A comma before and is right only when a full sentence follows. \"Threw to first base\" has no subject of its own.",
  },
);
